spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kimsangkyun/spring-cloud-config.git

  rabbitmq:
    host: localhost
    port: 5672
    username: ksk1004zz
    password: rlatkd11

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh, bus-env